# Generated by Django 5.2.1 on 2025-05-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_groupmessage_tag_groupmessage_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_image", models.FileField(upload_to="file/")),
                ("file_name", models.CharField(blank=True, max_length=30)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachment",
                        to="chat.groupmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageAttachement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_image", models.ImageField(upload_to="image/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "messages_chat_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_attachment",
                        to="chat.groupmessage",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Attachement",
        ),
    ]
