# Generated by Django 5.2.1 on 2025-05-28 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_rename_file_image_fileattachment_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileattachment",
            name="message",
        ),
        migrations.RemoveField(
            model_name="imageattachment",
            name="message",
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "reaction")},
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="message",
        ),
    ]
