# Generated by Django 5.1.6 on 2025-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
