# Generated by Django 5.1.4 on 2025-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ticket_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
