# Generated by Django 5.1.4 on 2025-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customer_agents_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agents",
            name="max_customer",
            field=models.IntegerField(default=1),
        ),
    ]
