# Generated by Django 5.1.4 on 2025-02-16 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_agents_max_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
