# Generated by Django 5.2.1 on 2025-05-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ticket_queued_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("assigned", "Assigned"),
                    ("progress", "Progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("assigned", "Assigned"),
                            ("progress", "Progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("new_queued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "new_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to="core.agent",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="core.ticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoEscalate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_escalate",
                        to="core.ticket",
                    ),
                ),
                (
                    "status_change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_escalate",
                        to="core.statuschange",
                    ),
                ),
            ],
        ),
    ]
