# Generated by Django 5.2.1 on 2025-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_ticket_status_statuschange_autoescalate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
