# Generated by Django 5.1.4 on 2025-02-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ticket_created_at_alter_ticket_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="status",
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("assigned", "Assigned"),
                    ("completed", "Completed"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_to_customer",
                to="core.customer",
            ),
        ),
    ]
