# Generated by Django 5.1.4 on 2025-02-18 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_customer_status_ticket_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="desc",
            new_name="issue_desc",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="title",
            new_name="issue_title",
        ),
        migrations.RemoveField(
            model_name="agents",
            name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="agents",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="name",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_customer",
        ),
        migrations.AddField(
            model_name="customer",
            name="solved_issue",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="agents",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_to_customer",
                to="core.agents",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_tickets",
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("assigned", "Assigned"),
                    ("progress", "Progress"),
                    ("completed", "Completed"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("agent", "Agent"), ("customer", "Customer")],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agents",
            name="agent_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_name",
                to="core.userdetails",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_name",
                to="core.userdetails",
            ),
        ),
    ]
