# Generated by Django 5.1.4 on 2025-02-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_desc_ticket_issue_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
