# Generated by Django 5.1.4 on 2025-02-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_ticket_ticket_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="email",
        ),
    ]
