services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: TEAM
      POSTGRES_PASSWORD: DEV
      POSTGRES_DB: SUPPORTIX
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
